backend:

  replicaCount: 1

  image: 
    repository: "europe-west1-docker.pkg.dev/threatmonit/threatmonit/backend"
    tag: "prod-28cb2ee"

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/whitelist-source-range: "161.97.106.132/32"
    hosts:
      - host: capi.threatmonit.io
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - secretName: backend-tls
      hosts:
        - capi.threatmonit.io

  service:
    type: ClusterIP
    port: 80
    targetPort: 8080

  resources: 
    limits:
      memory: 4Gi
    requests:
      cpu: 1
      memory: 2Gi
