backend:

  replicaCount: 2

  image: 
    repository: "nginx"
    tag: "latest"

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: nginx.sample.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - secretName: backend-tls
      hosts:
        - nginx.sample.com

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

  resources: 
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
