backend:

  replicaCount: 1

  image: 
    repository: "europe-west1-docker.pkg.dev/threatmonit/threatmonit/frontend"
    tag: ""

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: cdashboard.threatmonit.io
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - secretName: backend-tls
      hosts:
        - cdashboard.threatmonit.io

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

  resources: 
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
